# SPDX-FileCopyrightText: 2021-2024 The Refinery Authors <https://refinery.tools/>
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "Refinery"
SPDX-PackageSupplier = "Dániel Varró <daniel.varro@liu.se>"
SPDX-PackageDownloadLocation = "https://github.com/graphs4value/refinery"
